export const CHANGE_RENDER_DATA_ITEM='change_render_data_item'; // 改变图层数据事件,该事件的操作会存到步骤管理器里
export const REMOVE_EVENT_LISTENER='REMOVE_EVENT_LISTENER';
export const ADD_EVENT_LISTENER='ADD_EVENT_LISTENER';
export const LAYER_DRAG='LAYER_DRAG';// 图层拖拽事件 主要是操作rect等频繁触发的事件,不记录到步骤管理器中
export const ACTIVE_LAYER='ACTIVE_LAYER'; // 激活图层事件
export const CHANGE_COMPONENT_CONFIG='CHANGE_COMPONENT_CONFIG'; // 激活图层事件
export const REVERT_RENDER_DATA_ITEM='REVERT_RENDERDATA_ITEM'; // 激活图层事件
export const ADD_COMPONENT='ADD_COMPONENT'; // 添加组件事件
export const DELETE_COMPONENT='DELETE_COMPONENT'; // 删除组件事件
export const LOCK_COMPONENT='LOCK_COMPONENT'; // 锁定组件事件
export const HIDDEN_COMPONENT='HIDDEN_COMPONENT'; // 隐藏组件事件
export const CHANGE_RENDERDATA_ALL='CHANGE_RENDERDATA_ALL'; // 隐藏组件事件
export const DEFAULT_PAGE_NAME='DEFAULT_PAGE_NAME'; // 隐藏组件事件
export const ADD_PAGE_BACKGROUND_IMAGE='ADD_PAGE_BACKGROUND_IMAGE'; // 页码添加背景图片事件
export const CHANGE_PAGE_BACKGROUND_BG='CHANGE_PAGE_BACKGROUND_BG'; // 页码添加背景颜色
export const CHANGE_PAGE_BACKGROUND_OPACITY='CHANGE_PAGE_BACKGROUND_OPACITY'; // 页码改变透明度
export const CHANGE_EDITOR_SCALE='CHANGE_EDITOR_SCALE'; // 页码改变透明度
export const CHANGE_EDITOR_IMAGE_EVENT='CHANGE_EDITOR_IMAGE_EVENT'; // 页码改变透明度
export const GET_RENDER_DATA='get_render_data'; // 获取json
export const GET_RENDER_VIEW='GET_RENDER_VIEW'; // 获取json
export const SET_RENDER_VIEW='SET_RENDER_VIEW'; // 获取json
